### ISSUE TITLE
The tutorial

### ISSUE THREAD

**Issue by Qunliyau** [VDelv/Emotion-EEG#2]
can you share the address of the research report or paper? Thanks a lot

**Comment by VDelv** [comment]
Hi,

The final version of the paper is not available yet. 
But I can send you the preprint https://arxiv.org/abs/2201.03891 

Best

**Comment by Qunliyau** [comment]
> Hi,
> 
> The final version of the paper is not available yet. But I can send you the preprint https://arxiv.org/abs/2201.03891
> 
> Best

Thank you so much for your reply.
